name: Deployment Pipeline
on:
  push:
    branches: [ main ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Versioning Data
        id: versioning
        uses: Soumeh/Auto-Versioning@main

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Installing gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:${{ steps.versioning.outputs.tag }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:${{ steps.versioning.outputs.tag }}

      - name: Deploy to gcloud run
        run: |
          gcloud run deploy portfolio-website \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:${{ steps.versioning.outputs.tag }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --port=80


          
      
