name: Deployment Pipeline
on:
  push:
    branches: [ main ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Versioning Data
        id: versioning
        uses: Soumeh/Auto-Versioning@main

      - name: Installing gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Docker Build
        run: |
          docker build -t portfolio-website:${{ steps.versioning.outputs.tag }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Publish to DockerHub
        run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:${{ steps.versioning.outputs.tag }}

      - name: Deploy to gcloud run
        run: |
          gcloud run deploy portfolio-website \
            --image=${{ secrets.DOCKERHUB_USERNAME }}/portfolio-website:${{ steps.versioning.outputs.tag }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated


          
      
